apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"

resources:
  - base/
  - netpol-egress.yaml
  - service-entries.yaml
  - sidecar.yaml

helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    releaseName: airflow
    valuesFile: values.yaml
    version: 1.10.0
    includeCRDs: false
