apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-ingress

commonAnnotations:
  argocd.argoproj.io/sync-wave: "5"

resources:
  - base/

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx
    valuesFile: values.yaml
    version: 4.7.0
    includeCRDs: false
