# https://github.com/kubernetes/ingress-nginx/blob/helm-chart-4.7.0/charts/ingress-nginx/values.yaml
controller:
  service:
    enabled: true
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      service.beta.kubernetes.io/azure-load-balancer-internal: "false"
      service.beta.kubernetes.io/azure-dns-label-name: "browol-f7e389a4c9f3"
    enableHttp: false
    enableHttps: true
    externalTrafficPolicy: Cluster
  admissionWebhooks:
    patch:
      enabled: true
      podAnnotations:
        sidecar.istio.io/inject: "false"
  nodeSelector:
    role: worker
  tolerations:
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot
  configAnnotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
