apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-istio-system

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  - base/
  - istioctl-generated.yaml
  - peerauthentication.yaml
  - sidecar.yaml
