apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: infra-istio-system
spec:
  egress:
    - hosts:
        - "./*"
        - "default/*"
        - "kube-system/*"
        - "infra-istio-system/*"
        - "infra-ingress/*"
